steps:
  - label : ":kubekite: Build Binary"
    command: "./.buildkite/scripts/build-binary.sh"

  - wait

  - label: ":kubekite: Build Image"
    command: "./.buildkite/scripts/build-image.sh"
    env:
      IMAGE_NAME: asia.gcr.io/test-project-buildkite/kubekite

  - wait

  - label: ":kubekite: Deploy to Kube"
    command: "./.buildkite/scripts/deploy-image.sh"
